# This is a basic workflow to help you get started with Actions

# name: ğŸ¡ Slides generation and ğŸ† deployment to Github Pages

# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Run a multi-line script
#         run: npx slidev
